<a href="https://colab.research.google.com/github/mariliazago0/fundamentos01/blob/main/notebooks/encontro01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
!pip install tinydb

Requirement already satisfied: tinydb in /usr/local/lib/python3.12/dist-packages (4.8.2)

In [28]:
# programas/bibliotecas utilizados no script/codigo
import httpx # Responsável pelas requisições web
from bs4 import BeautifulSoup # Responsável por realizar o web scraping (coletar os dados)
from tinydb import TinyDB, Query

In [29]:
def inserir_no_banco(dados, link_noticia):
  arquivo_banco_dados = "nota_mre.json"
  db = TinyDB(arquivo_banco_dados)


  # Evitar dados repetidos no banco
  Buscar = Query()
  verificar_link = db.contains(Buscar.link == link_noticia)

  if not verificar_link:
    print("Inserindo nova informação no banco")
    db.insert(dados)
  else:
    print("Link já existe no banco. Esta informação não será inserida novamente")

In [30]:
# Variável e tipos de dados (string, lista, numero)
paginas = ["https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/notas-a-imprensa?b_start:int=0"]

def acessa_pagina (link):
  print (f"Estamos na pagina:{link}")

  # Define headers para a requisição, simulando um navegador
  headers = {
      'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
      'Accept-Language': 'en-US,en;q=0.9',
      'Accept-Encoding': 'gzip, deflate, br',
      'Connection': 'keep-alive',
  }

  timeout = httpx.Timeout(connect=20.0, read=30.0, write=20.0, pool=10.0)
  pag_web = httpx.get(link, headers=headers, timeout=timeout)
  bs = BeautifulSoup(pag_web, "html.parser")
  return bs

# loop for
# beautifulsoap >> find e find_all

for pagina in paginas:
  pagina_inteira = acessa_pagina(pagina)
  lista_noticias = pagina_inteira.find("div", attrs={"id": "content-core"}).find_all("article")
  for noticia in lista_noticias:
    # titulo
    try:
      titulo = noticia.find("h2", attrs={"class": "tileHeadline"}).text.strip()
      print(titulo)
    except:
        titulo = ""

    #link
    try:
      link_noticia = noticia.a["href"]
      print(link_noticia)
    except:
      link_noticia = ""
    # numero da nota - exemplo: NOTA À IMPRENSA Nº 72
    # numero da nota - exemplo: NOTA À IMPRENSA N° 590
    num_nota = noticia.find("span", attrs={"class": "subtitle"}).text.strip()
    # print(num_nota)
    # num_nota = noticia.find(attrs={"class": "subtitle"}).text.strip()
    num_nota = num_nota.replace("NOTA À IMPRENSA N°", "").replace("NOTA À IMPRENSA Nº", "").strip()
    print(num_nota)
    print("###")
    # data
    # horário
    data_hora = noticia.find_all("span",attrs={"class": "summary-view-icon"})
    data= data_hora[0].text.strip()
    hora = data_hora[1].text.strip()
    print(data)
    print(hora)
    conteudo = acessa_pagina (link_noticia)
    paragrafos = conteudo.find("div", attrs={"property":"rnews:articleBody"}).find_all("p")
    lista_paragrafos = []
    for paragrafo in paragrafos:
      lista_paragrafos.append(paragrafo.text.strip())
    print(lista_paragrafos)
    # função para inserir dados coletados no banco
    dados = {
        "titulo": titulo,
        "link": link_noticia,
        "data": data,
        "hora": hora,
        "num_nota": num_nota,
        "paragrafo": lista_paragrafos
    }
    inserir_no_banco(dados,link_noticia)

Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/notas-a-imprensa?b_start:int=0
Abertura de mercado para o Brasil no Chile - Nota Conjunta MRE/MAPA
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/abertura-de-mercado-para-o-brasil-no-chile-nota-conjunta-mre-mapa
150
###
29/04/2026
17h49
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/abertura-de-mercado-para-o-brasil-no-chile-nota-conjunta-mre-mapa
['O governo brasileiro concluiu negociações que permitirão ao Brasil exportar grãos secos de destilaria (DDG/DDGS) para o Chile.', 'A abertura beneficia importante insumo agrícola gerado a partir da produção de etanol de milho. Os grãos secos de destilaria (DDG/DDGS) são utilizados na produção de ração para aves, bovinos e suínos.', 'Em 2025, o Brasil exportou mais de US$ 2,2 bilhões em produtos agropecuários para o Chile, com destaque para carnes, produtos florestais e o complexo soja.', 'Com esse anúncio, o agronegócio brasileiro alcança 601 aberturas de mercado desde 2023.', 'Tais resultados são fruto do trabalho conjunto entre o Ministério das Relações Exteriores (MRE) e o Ministério da Agricultura e Pecuária (MAPA).']
Inserindo nova informação no banco
Promulgação do Acordo Provisório de Comércio entre o MERCOSUL e a União Europeia – Nota Conjunta MRE/MDIC/MAPA
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/promulgacao-do-acordo-provisorio-de-comercio-entre-o-mercosul-e-a-uniao-europeia-2013-nota-conjunta-mre-mdic-mapa
149
###
28/04/2026
19h20
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/promulgacao-do-acordo-provisorio-de-comercio-entre-o-mercosul-e-a-uniao-europeia-2013-nota-conjunta-mre-mdic-mapa
['O Presidente Luiz Inácio Lula da Silva assinou hoje (28/04) Decreto que incorpora o Acordo Provisório de Comércio entre o MERCOSUL e a União Europeia ao ordenamento jurídico brasileiro.\xa0Fruto de mais de 25 anos de negociações, o Acordo é um marco histórico para os dois blocos, que estabelecem, a partir do início de sua aplicação provisória, em 1º de maio, uma das maiores áreas de livre comércio do planeta, composta por 31 países, 720 milhões de pessoas e um PIB combinado que ultrapassa os US$ 22 trilhões.\xa0A ágil promulgação do Acordo MERCOSUL-UE reflete a prioridade dada ao tema pelo Presidente Lula desde o início de seu terceiro mandato. O Acordo beneficiará toda a sociedade brasileira, ao contribuir para a expansão das nossas parcerias globais, o aumento e a diversificação das nossas exportações, a redução de custos para produtores e consumidores e a geração de renda e de novas oportunidades para trabalhadores e empresas.Acesse aqui o factsheet sobre o Acordo.']
Inserindo nova informação no banco
Mortes de brasileiros no Líbano em decorrência de ataques israelenses
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/mortes-de-brasileiros-no-libano-em-decorrencia-de-ataques-israelenses
148
###
27/04/2026
19h04
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/mortes-de-brasileiros-no-libano-em-decorrencia-de-ataques-israelenses
['O governo brasileiro tomou conhecimento, com consternação e pesar, das mortes, em 26/4, de criança brasileira, de 11 anos, de sua mãe, também brasileira, e de seu pai libanês, vítimas de ataque das Forças de Defesa de Israel. Outro filho do casal, igualmente brasileiro, encontra-se hospitalizado. A família encontrava-se em sua residência, no distrito de Bint Jbeil, no Sul do Líbano, no momento do bombardeio.', 'Esse ataque constitui mais um exemplo das reiteradas e inaceitáveis violações ao cessar-fogo anunciado em 16 de abril, as quais já resultaram na morte de dezenas de civis libaneses, incluindo mulheres e crianças, assim como de uma jornalista e de dois integrantes franceses da Força Interina das Nações Unidas no Líbano (UNIFIL).', 'Ao expressar sinceras condolências aos familiares das vítimas, o Brasil reitera sua mais veemente condenação a todos os ataques perpetrados durante a vigência do cessar-fogo, tanto por parte das forças israelenses quanto do Hezbollah. Condena, ainda, as demolições sistemáticas de residências e de outras estruturas civis no sul do Líbano, levadas a efeito, ao longo das últimas semanas, pelas forças israelenses, e a persistência do deslocamento forçado de mais de um milhão de libaneses.', 'Nesse contexto, o Brasil exorta as partes ao cumprimento integral dos termos da Resolução 1701 (2006) do Conselho de Segurança das Nações Unidas, que estabeleceu os termos do cessar-fogo que encerrou a guerra de 2006, e à imediata cessação das hostilidades, com a retirada completa das forças israelenses do território libanês.', 'A Embaixada do Brasil em Beirute está em contato com a família dos brasileiros falecidos para prestar assistência consular, incluindo para o filho hospitalizado.']
Inserindo nova informação no banco
Ataques terroristas no Mali
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/ataques-terroristas-no-mali
147
###
27/04/2026
13h38
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/ataques-terroristas-no-mali
['O Governo brasileiro manifesta grave preocupação com os ataques terroristas ocorridos no último fim de semana em seis cidades do Mali, incluindo a capital Bamako, que vitimaram um número ainda impreciso de civis e militares, entre os quais o ministro da Defesa daquele país, General Sadio Camara.Ao manifestar sinceras condolências às famílias das vítimas e o desejo de pronta recuperação aos feridos, o Brasil reitera o firme repúdio a todo ato de terrorismo, sob qualquer pretexto.Não se tem notícia de cidadãos brasileiros entre as vítimas dos ataques. O plantão consular da embaixada do Brasil em Bamako é +223 74 74 95 24.']
Inserindo nova informação no banco
Atentado na Colômbia
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/atentado-na-colombia-1
146
###
27/04/2026
08h45
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/atentado-na-colombia-1
['O governo brasileiro condena o ataque perpetrado no Departamento de Cauca, na Colômbia, em 25 de abril, que deixou mais de uma dezena de mortos e vários feridos.O governo brasileiro manifesta sua solidariedade às famílias das vítimas e ao povo e governo colombianos.O Brasil reafirma, ainda, o seu apoio ao\xa0 "Compromisso com um processo eleitoral livre e em paz na Colombia", iniciativa da Defensoria do Povo da Colômbia endossada pelo Escritório do Alto Comissário das Nações Unidas na Colômbia para Direitos Humanos, pela Missão de Apoio ao Processo de Paz na Colômbia da Organização dos Estados Americanos (MAPP-OEA), pela Missão de Verificação das Nações Unidas na Colômbia (UNVMC), pela Conferência Episcopal colombiana e por outras missões diplomáticas em Bogotá.Não há registro de nacionais brasileiros entre as vítimas do atentado.']
Inserindo nova informação no banco
Apresentação da candidatura do Professor George Rodrigo Bandeira Galindo ao Tribunal Internacional do Direito do Mar
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/apresentacao-da-candidatura-do-professor-george-rodrigo-bandeira-galindo-ao-tribunal-internacional-do-direito-do-mar
145
###
24/04/2026
15h57
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/apresentacao-da-candidatura-do-professor-george-rodrigo-bandeira-galindo-ao-tribunal-internacional-do-direito-do-mar
['Realizou-se, em 23 de abril, coquetel de apresentação da candidatura do Professor George Rodrigo Bandeira Galindo ao Tribunal Internacional do Direito do Mar (TIDM), para o mandato 2026-2035. O evento contou com a participação do Ministro das Relações Exteriores, Mauro Vieira, e do Presidente do Superior Tribunal de Justiça, Ministro Herman Benjamin.', 'Com sede em Hamburgo, na Alemanha, o TIDM, foi estabelecido pela Convenção das Nações Unidas para o Direito do Mar (CNUDM). Possui jurisdição sobre qualquer disputa relacionada à interpretação e à aplicação da CNUDM, bem como sobre todo e qualquer caso em que exista acordo que reconheça a jurisdição do Tribunal, como o Acordo de Pesca de Nova York. Além dos Estados e Organizações Internacionais que são Partes da CNUDM, o Tribunal também é aberto a Estados ou organizações internacionais que não aderiram à Convenção.', 'Na ocasião, os representantes das Embaixadas dos Estados Partes do TIDM acreditados em Brasília puderam conhecer melhor a plataforma de atuação proposta pelo candidato brasileiro, pautada por enfoque imparcial, independente e técnico, com vistas à preservação e ao aprimoramento da institucionalidade da CNUDM.']
Inserindo nova informação no banco
Aberturas de mercado para o Brasil em Cuba, nas Filipinas e na Coreia do Sul
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/aberturas-de-mercado-para-o-brasil-em-cuba-nas-filipinas-e-na-coreia-do-sul
144
###
24/04/2026
15h48
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/aberturas-de-mercado-para-o-brasil-em-cuba-nas-filipinas-e-na-coreia-do-sul
['O governo brasileiro concluiu negociações que permitirão a exportação de diversos produtos para Cuba, Filipinas e Coreia do Sul.', 'Em Cuba, foi autorizada a exportação de carne bovina e suína com osso. Em 2025, o Brasil exportou mais de US$ 255 milhões em produtos do agronegócio para o país.', 'Nas Filipinas, país para o qual o Brasil exportou cerca de US$ 1,8 bilhão em produtos agropecuários no ano passado, as autoridades locais aprovaram a exportação de carne bovina resfriada com e sem osso.', 'Na Coreia do Sul, obteve-se abertura de mercado para exportação de castanha-do-brasil com e sem casca, de castanha de baru e de castanha de caju. Extraídos de forma sustentável, esses produtos beneficiarão economicamente as comunidades envolvidas em suas cadeias produtivas. Em 2025, o Brasil exportou mais de US$ 2,4 bilhões em produtos agropecuários para o país.', 'Com estes anúncios, o agronegócio brasileiro alcança 600 aberturas de mercado desde o início de 2023.', 'Tais resultados são fruto do trabalho conjunto entre o Ministério das Relações Exteriores (MRE) e o Ministério da Agricultura e Pecuária (MAPA).']
Inserindo nova informação no banco
Aberturas de mercado para o Brasil no Togo - Nota Conjunta MRE/MAPA
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/aberturas-de-mercado-para-o-brasil-no-togo-nota-conjunta-mre-mapa
143
###
22/04/2026
19h20
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/aberturas-de-mercado-para-o-brasil-no-togo-nota-conjunta-mre-mapa
['O governo brasileiro concluiu negociações que permitirão a exportação de material genético bovino (sêmen e embriões) para o Togo.As aberturas criam oportunidades para produtores brasileiros, bem como para a prestação de serviços de consultoria e assistência técnica. Em 2025, o Brasil exportou mais de US$ 148 milhões em produtos agropecuários para o Togo, com destaque para produtos do complexo sucroalcooleiro, carnes e couro.Com esse anúncio, o agronegócio brasileiro alcança 594 aberturas de mercado desde o início de 2023.Tais resultados são fruto do trabalho conjunto entre o Ministério das Relações Exteriores (MRE) e o Ministério da Agricultura e Pecuária (MAPA).']
Inserindo nova informação no banco
Atos adotados por ocasião da Visita de Estado do Presidente Luiz Inácio Lula da Silva a Hannover - Alemanha, 19 e 20 de abril de 2026
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/atos-adotados-por-ocasiao-da-visita-de-estado-do-presidente-luiz-inacio-lula-da-silva-a-hannover-alemanha-19-e-20-de-abril-de-2026-2
142
###
20/04/2026
13h13
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/atos-adotados-por-ocasiao-da-visita-de-estado-do-presidente-luiz-inacio-lula-da-silva-a-hannover-alemanha-19-e-20-de-abril-de-2026-2
['Foram adotados\xa0os seguintes atos por ocasião\xa0da visita do Presidente\xa0Luiz Inácio Lula da Silva a Hannover - Alemanha, em 19 e 20 de abril de 2026:']
Inserindo nova informação no banco
Declaração Conjunta Brasil-Alemanha sobre apoio ao Fundo Florestas Tropicais para Sempre (TFFF) - Hannover, 20 de abril de 2026
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/declaracao-conjunta-brasil-alemanha-sobre-apoio-ao-fundo-florestas-tropicais-para-sempre-tfff-hannover-20-de-abril-de-2026-1
141
###
20/04/2026
11h12
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/declaracao-conjunta-brasil-alemanha-sobre-apoio-ao-fundo-florestas-tropicais-para-sempre-tfff-hannover-20-de-abril-de-2026-1
['No contexto da reunião bilateral entre o Presidente da República, Luiz Inácio Lula da Silva, e o Chanceler Federal da Alemanha, Friedrich Merz, realizada em Hannover, em 20 de abril de 2026, ambos os Governos reafirmaram seu compromisso compartilhado com a conservação e o uso sustentável das florestas tropicais como elemento central para o enfrentamento dos desafios ambientais globais.', 'O Fundo Florestas Tropicais para Sempre (TFFF) é um mecanismo inovador de financiamento concebido para proporcionar aos países com florestas tropicais apoio financeiro de longo prazo, por meio de pagamentos por resultados comprovados de conservação e restauração florestal. Baseia-se em critérios transparentes, dados robustos, salvaguardas sólidas e na participação significativa de Povos Indígenas e Comunidades tradicionais, articulando a proteção da natureza e do clima com o desenvolvimento sustentável e o combate à pobreza.', 'A Alemanha manifestou apreço pela liderança do Brasil no avanço do TFFF, que culminou em seu lançamento na Cúpula do Clima de Belém, em 6 de novembro de 2025. A Declaração de Lançamento foi endossada por 67 países, inclusive países que abrigam mais de 90% da cobertura de florestas tropicais em países em desenvolvimento, com compromissos de aporte ao capital júnior superiores a USD 6,7 bilhões.', 'Contribuição alemã', 'A Alemanha apoia o TFFF, tanto política quanto financeiramente, como elemento-chave da arquitetura global do clima, da biodiversidade e das florestas. Com base em seu engajamento de longa data no financiamento florestal e climático, a Alemanha já aportou EUR 20 milhões a um fundo do Banco Mundial para ajudar a lançar o TFFF.', 'A partir de 2027, o governo alemão pretende aportar, ao todo, EUR 1 bilhão ao Tropical Forest Investment Fund (TFIF), por meio do KfW, na qualidade de administrador fiduciário. O governo alemão incluirá a contribuição alemã na preparação do orçamento de 2027 do Fundo para o Clima e a Transformação. Até a conclusão desse processo, a contribuição alemã estará sujeita à aprovação orçamentária e parlamentar.', 'Contribuição brasileira', 'O Brasil foi o primeiro país a anunciar aporte ao TFFF, com o Presidente Lula tendo anunciado, em setembro de 2025, um investimento de USD 1 bilhão, que virá do orçamento do Fundo Clima do Brasil e será operacionalizado com o apoio de bancos públicos de desenvolvimento. O Brasil avalia que o modelo financeiro do TFFF é robusto e o considera um mecanismo inovador e escalável para alavancar a participação do setor privado no financiamento ambiental, ao mesmo tempo em que reconhece a necessidade de contribuições públicas para reduzir os riscos dos investimentos.', 'Ao criar valor econômico tangível para manter florestas tropicais em pé, o TFFF gerará incentivos para sua conservação, ao mesmo tempo em que proporcionará um fluxo adicional e previsível de financiamento para apoiar os países em desenvolvimento na implementação de políticas e programas correlatos.', 'Perspectivas e próximos passos', 'A Alemanha e o Brasil continuarão a trabalhar conjuntamente com outros países patrocinadores e com países com florestas tropicais para tornar o Fundo e seu braço financeiro, o TFIF, operacionais com a maior brevidade possível, inclusive por meio do avanço da consolidação e da institucionalização de suas estruturas jurídicas e financeiras.', 'Ambos os governos seguem engajando as lideranças de potenciais países patrocinadores com vistas a avançar na capitalização do TFFF.', 'Ambos os Governos estão comprometidos com a integração do TFFF à arquitetura internacional mais ampla de financiamento ambiental e com a criação de sinergias com fundos e iniciativas existentes. As duas partes sublinham que o TFIF dispõe de um modelo financeiro sólido e robusto, que permitirá ao TFFF tornar-se, ao longo do tempo, importante vetor para o alcance dos objetivos ambientais globais.']
Inserindo nova informação no banco
III Consultas Intergovernamentais de Alto Nível Brasil-Alemanha - Declaração Conjunta -  Hannover, 20 de abril de 2026
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/iii-consultas-intergovernamentais-de-alto-nivel-brasil-alemanha-declaracao-conjunta-hannover-20-de-abril-de-2026
140
###
20/04/2026
10h26
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/iii-consultas-intergovernamentais-de-alto-nivel-brasil-alemanha-declaracao-conjunta-hannover-20-de-abril-de-2026

In [31]:
import pandas as pd
import json

## Abrindo o rquivo json
with open("nota_mre.json") as f:
  raw = json.load(f)

df = pd.DataFrame.from_dict(raw["_default"], orient="index")

df

,titulo,link,data,hora,num_nota,paragrafo
1,Abertura de mercado para o Brasil no Chile - N...,https://www.gov.br/mre/pt-br/canais_atendiment...,29/04/2026,17h49,150,[O governo brasileiro concluiu negociações que...
2,Promulgação do Acordo Provisório de Comércio e...,https://www.gov.br/mre/pt-br/canais_atendiment...,28/04/2026,19h20,149,[O Presidente Luiz Inácio Lula da Silva assino...
3,Mortes de brasileiros no Líbano em decorrência...,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,19h04,148,"[O governo brasileiro tomou conhecimento, com ..."
4,Ataques terroristas no Mali,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,13h38,147,[O Governo brasileiro manifesta grave preocupa...
5,Atentado na Colômbia,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,08h45,146,[O governo brasileiro condena o ataque perpetr...
6,Apresentação da candidatura do Professor Georg...,https://www.gov.br/mre/pt-br/canais_atendiment...,24/04/2026,15h57,145,"[Realizou-se, em 23 de abril, coquetel de apre..."
7,"Aberturas de mercado para o Brasil em Cuba, na...",https://www.gov.br/mre/pt-br/canais_atendiment...,24/04/2026,15h48,144,[O governo brasileiro concluiu negociações que...
8,Aberturas de mercado para o Brasil no Togo - N...,https://www.gov.br/mre/pt-br/canais_atendiment...,22/04/2026,19h20,143,[O governo brasileiro concluiu negociações que...
9,Atos adotados por ocasião da Visita de Estado ...,https://www.gov.br/mre/pt-br/canais_atendiment...,20/04/2026,13h13,142,[Foram adotados os seguintes atos por ocasião ...
10,Declaração Conjunta Brasil-Alemanha sobre apoi...,https://www.gov.br/mre/pt-br/canais_atendiment...,20/04/2026,11h12,141,[No contexto da reunião bilateral entre o Pres...
11,III Consultas Intergovernamentais de Alto Níve...,https://www.gov.br/mre/pt-br/canais_atendiment...,20/04/2026,10h26,140,[1. Sob a presidência do Chanceler Federal Fri...
12,4ª Reunião de Alto Nível do Fórum Democracia S...,https://www.gov.br/mre/pt-br/canais_atendiment...,19/04/2026,07h58,139,"[Nosotras y nosotros, los Jefes de Estado y de..."
13,Declaração Conjunta Sobre a Situação em Cuba,https://www.gov.br/mre/pt-br/canais_atendiment...,18/04/2026,16h44,138,[À luz da evolução da situação em Cuba e das c...
14,Visita Oficial do Senhor Presidente da Repúbli...,https://www.gov.br/mre/pt-br/canais_atendiment...,18/04/2026,11h33,137,[O senhor Presidente da República realizará vi...
15,Cessar-fogo no Líbano,https://www.gov.br/mre/pt-br/canais_atendiment...,17/04/2026,15h23,136,[O governo brasileiro saúda o anúncio de cessa...
16,Abertura de mercado para o Brasil no Vietnã - ...,https://www.gov.br/mre/pt-br/canais_atendiment...,17/04/2026,12h31,135,[O governo brasileiro concluiu negociações com...
17,Atos adotados por ocasião da Visita de Estado ...,https://www.gov.br/mre/pt-br/canais_atendiment...,17/04/2026,11h27,134,"[Foram adotados os seguintes atos, por ocasião..."
18,Declaração Conjunta por ocasião da I Cúpula Es...,https://www.gov.br/mre/pt-br/canais_atendiment...,17/04/2026,11h02,133,"[., I CÚPULA ESPANHA-BRASIL, Declaração conjun..."
19,Ataques a Tiros em Escolas na Turquia,https://www.gov.br/mre/pt-br/canais_atendiment...,16/04/2026,17h56,132,"[O Governo brasileiro tomou conhecimento, com ..."
20,Visita oficial do senhor Presidente da Repúbli...,https://www.gov.br/mre/pt-br/canais_atendiment...,16/04/2026,11h51,131,"[Nos dias 19 e 20 de abril, o senhor President..."
21,Visita oficial do senhor Presidente da Repúbli...,https://www.gov.br/mre/pt-br/canais_atendiment...,15/04/2026,21h20,130,"[Realizar-se-á em Barcelona, em 17 de abril co..."
22,Aberturas de mercado para o Brasil na Arábia S...,https://www.gov.br/mre/pt-br/canais_atendiment...,15/04/2026,18h30,129,[O governo brasileiro concluiu negociações que...
23,Concessão de agrément ao Embaixador designado ...,https://www.gov.br/mre/pt-br/canais_atendiment...,15/04/2026,12h31,128,"[O governo brasileiro informa, com satisfação,..."
24,Chuvas em Angola,https://www.gov.br/mre/pt-br/canais_atendiment...,14/04/2026,21h24,127,"[O governo brasileiro tomou conhecimento, com ..."
25,"Aberturas de mercado para o Brasil no Vietnã, ...",https://www.gov.br/mre/pt-br/canais_atendiment...,14/04/2026,20h10,126,[O governo brasileiro concluiu negociações que...
26,Acidente em ponto turístico no Haiti,https://www.gov.br/mre/pt-br/canais_atendiment...,12/04/2026,21h40,125,"[O governo brasileiro tomou conhecimento, com ..."
27,Estratégia de Cooperação do Rio de Janeiro,https://www.gov.br/mre/pt-br/canais_atendiment...,09/04/2026,16h30,124,"[, *, ESTRATÉGIA DE COOPERAÇÃO DO RIO DE JANEI..."
28,Convenção para a proteção do Meio Ambiente Mar...,https://www.gov.br/mre/pt-br/canais_atendiment...,09/04/2026,16h17,123,"[., CONVENÇÃO PARA A PROTEÇÃO DO MEIO AMBIENTE..."
29,Declaração do Rio de Janeiro - 9 de abril de 2026,https://www.gov.br/mre/pt-br/canais_atendiment...,09/04/2026,15h55,122,"[, *, DECLARAÇÃO DO RIO DE JANEIRO, , Nós, os ..."
30,Continuidade dos ataques israelenses contra o ...,https://www.gov.br/mre/pt-br/canais_atendiment...,08/04/2026,18h05,121,[O Governo brasileiro condena os mais recentes...

In [32]:
# saber quantidade de linhas e colunas do dataframe
df.shape

(30, 6)

In [33]:
# saber colunas disponiveis
df.columns

Index(['titulo', 'link', 'data', 'hora', 'num_nota', 'paragrafo'], dtype='object')

In [34]:
# selecionar uma coluna em especifico
df["titulo"]

1     Abertura de mercado para o Brasil no Chile - N...
2     Promulgação do Acordo Provisório de Comércio e...
3     Mortes de brasileiros no Líbano em decorrência...
4                           Ataques terroristas no Mali
5                                  Atentado na Colômbia
6     Apresentação da candidatura do Professor Georg...
7     Aberturas de mercado para o Brasil em Cuba, na...
8     Aberturas de mercado para o Brasil no Togo - N...
9     Atos adotados por ocasião da Visita de Estado ...
10    Declaração Conjunta Brasil-Alemanha sobre apoi...
11    III Consultas Intergovernamentais de Alto Níve...
12    4ª Reunião de Alto Nível do Fórum Democracia S...
13         Declaração Conjunta Sobre a Situação em Cuba
14    Visita Oficial do Senhor Presidente da Repúbli...
15                                Cessar-fogo no Líbano
16    Abertura de mercado para o Brasil no Vietnã - ...
17    Atos adotados por ocasião da Visita de Estado ...
18    Declaração Conjunta por ocasião da I Cúpula Es...
19                Ataques a Tiros em Escolas na Turquia
20    Visita oficial do senhor Presidente da Repúbli...
21    Visita oficial do senhor Presidente da Repúbli...
22    Aberturas de mercado para o Brasil na Arábia S...
23    Concessão de agrément ao Embaixador designado ...
24                                     Chuvas em Angola
25    Aberturas de mercado para o Brasil no Vietnã, ...
26                 Acidente em ponto turístico no Haiti
27           Estratégia de Cooperação do Rio de Janeiro
28    Convenção para a proteção do Meio Ambiente Mar...
29    Declaração do Rio de Janeiro - 9 de abril de 2026
30    Continuidade dos ataques israelenses contra o ...
Name: titulo, dtype: object

In [35]:

# delimitar colunas do dataframe
df_delimitado = df[["titulo", "data"]]
df_delimitado

                                               titulo        data
1   Abertura de mercado para o Brasil no Chile - N...  29/04/2026
2   Promulgação do Acordo Provisório de Comércio e...  28/04/2026
3   Mortes de brasileiros no Líbano em decorrência...  27/04/2026
4                         Ataques terroristas no Mali  27/04/2026
5                                Atentado na Colômbia  27/04/2026
6   Apresentação da candidatura do Professor Georg...  24/04/2026
7   Aberturas de mercado para o Brasil em Cuba, na...  24/04/2026
8   Aberturas de mercado para o Brasil no Togo - N...  22/04/2026
9   Atos adotados por ocasião da Visita de Estado ...  20/04/2026
10  Declaração Conjunta Brasil-Alemanha sobre apoi...  20/04/2026
11  III Consultas Intergovernamentais de Alto Níve...  20/04/2026
12  4ª Reunião de Alto Nível do Fórum Democracia S...  19/04/2026
13       Declaração Conjunta Sobre a Situação em Cuba  18/04/2026
14  Visita Oficial do Senhor Presidente da Repúbli...  18/04/2026
15                              Cessar-fogo no Líbano  17/04/2026
16  Abertura de mercado para o Brasil no Vietnã - ...  17/04/2026
17  Atos adotados por ocasião da Visita de Estado ...  17/04/2026
18  Declaração Conjunta por ocasião da I Cúpula Es...  17/04/2026
19              Ataques a Tiros em Escolas na Turquia  16/04/2026
20  Visita oficial do senhor Presidente da Repúbli...  16/04/2026
21  Visita oficial do senhor Presidente da Repúbli...  15/04/2026
22  Aberturas de mercado para o Brasil na Arábia S...  15/04/2026
23  Concessão de agrément ao Embaixador designado ...  15/04/2026
24                                   Chuvas em Angola  14/04/2026
25  Aberturas de mercado para o Brasil no Vietnã, ...  14/04/2026
26               Acidente em ponto turístico no Haiti  12/04/2026
27         Estratégia de Cooperação do Rio de Janeiro  09/04/2026
28  Convenção para a proteção do Meio Ambiente Mar...  09/04/2026
29  Declaração do Rio de Janeiro - 9 de abril de 2026  09/04/2026
30  Continuidade dos ataques israelenses contra o ...  08/04/2026

In [36]:

# primeiras (head), ultimas (tail) e linhas aleatórias (sample)
df.head(10)

,titulo,link,data,hora,num_nota,paragrafo
1,Abertura de mercado para o Brasil no Chile - N...,https://www.gov.br/mre/pt-br/canais_atendiment...,29/04/2026,17h49,150,[O governo brasileiro concluiu negociações que...
2,Promulgação do Acordo Provisório de Comércio e...,https://www.gov.br/mre/pt-br/canais_atendiment...,28/04/2026,19h20,149,[O Presidente Luiz Inácio Lula da Silva assino...
3,Mortes de brasileiros no Líbano em decorrência...,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,19h04,148,"[O governo brasileiro tomou conhecimento, com ..."
4,Ataques terroristas no Mali,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,13h38,147,[O Governo brasileiro manifesta grave preocupa...
5,Atentado na Colômbia,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,08h45,146,[O governo brasileiro condena o ataque perpetr...
6,Apresentação da candidatura do Professor Georg...,https://www.gov.br/mre/pt-br/canais_atendiment...,24/04/2026,15h57,145,"[Realizou-se, em 23 de abril, coquetel de apre..."
7,"Aberturas de mercado para o Brasil em Cuba, na...",https://www.gov.br/mre/pt-br/canais_atendiment...,24/04/2026,15h48,144,[O governo brasileiro concluiu negociações que...
8,Aberturas de mercado para o Brasil no Togo - N...,https://www.gov.br/mre/pt-br/canais_atendiment...,22/04/2026,19h20,143,[O governo brasileiro concluiu negociações que...
9,Atos adotados por ocasião da Visita de Estado ...,https://www.gov.br/mre/pt-br/canais_atendiment...,20/04/2026,13h13,142,[Foram adotados os seguintes atos por ocasião ...
10,Declaração Conjunta Brasil-Alemanha sobre apoi...,https://www.gov.br/mre/pt-br/canais_atendiment...,20/04/2026,11h12,141,[No contexto da reunião bilateral entre o Pres...

In [37]:
df.describe(include="all")

,titulo,link,data,hora,num_nota,paragrafo
count,30,30,30,30,30,30
unique,30,30,15,28,30,30
top,Abertura de mercado para o Brasil no Chile - N...,https://www.gov.br/mre/pt-br/canais_atendiment...,17/04/2026,19h20,150,[O governo brasileiro concluiu negociações que...
freq,1,1,4,2,1,1

In [38]:
df.isnull().sum()

titulo       0
link         0
data         0
hora         0
num_nota     0
paragrafo    0
dtype: int64

In [39]:
# verificar linhas duplicadas
df.duplicated().sum()

TypeError: unhashable type: 'list'