<a href="https://colab.research.google.com/github/mariliazago0/fundamentos01/blob/main/notebooks/encontro01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!pip install tinydb

Requirement already satisfied: tinydb in /usr/local/lib/python3.12/dist-packages (4.8.2)

In [22]:
import httpx # Responsável pelas requisições web
from bs4 import BeautifulSoup # Responsável por realizar o web scraping (coletar os dados)
from tinydb import TinyDB, Query
import urllib.parse # Para juntar URLs de forma robusta
import time # Para adicionar pausas entre as requisições
import re # Para usar expressões regulares na busca por links de paginação

def inserir_no_banco(dados, link_noticia):
  arquivo_banco_dados = "nota_china.json"
  db = TinyDB(arquivo_banco_dados)


  # Evitar dados repetidos no banco
  Buscar = Query()
  verificar_link = db.contains(Buscar.link == link_noticia)

  if not verificar_link:
    print("Inserindo nova informação no banco")
    db.insert(dados)
  else:
    print("Link já existe no banco. Esta informação não será inserida novamente")

In [23]:
# Variável e tipos de dados (string, lista, numero)

def acessa_pagina (link):
  print (f"Estamos na pagina: {link}")

  # Define headers para a requisição, simulando um navegador
  headers = {
      'User-Agent': "Mozilla/50 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
      'Accept-Language': 'en-US,en;q=0.9',
      'Accept-Encoding': 'gzip, deflate, br',
      'Connection': 'keep-alive',
  }

  timeout = httpx.Timeout(connect=20.0, read=30.0, write=20.0, pool=10.0)
  try:
    pag_web = httpx.get(link, headers=headers, timeout=timeout)
    pag_web.raise_for_status() # Levanta um erro para respostas HTTP ruins (4xx ou 5xx)
    bs = BeautifulSoup(pag_web.text, "html.parser") # Passar pag_web.text
    return bs
  except httpx.HTTPStatusError as e:
    print(f"Erro HTTP ao acessar {link}: {e}")
    return None
  except httpx.RequestError as e:
    print(f"Erro de requisição ao acessar {link}: {e}")
    return None

# loop for
# beautifulsoap >> find e find_all

base_site_url = "https://english.news.cn/"
initial_page_url = "https://english.news.cn/list/china-science.htm"
current_page_url = initial_page_url
paginas_visitadas = set()
max_paginas_a_visitar = 5 # Limite para evitar sobrecarga e loops infinitos

while current_page_url and len(paginas_visitadas) < max_paginas_a_visitar:
    if current_page_url in paginas_visitadas:
        print(f"WARNING: URL {current_page_url} já visitada. Parando para evitar loop infinito.")
        break
    paginas_visitadas.add(current_page_url)

    print(f"Processando página: {current_page_url} (Página {len(paginas_visitadas)} de {max_paginas_a_visitar})")
    pagina_inteira = acessa_pagina(current_page_url)

    if pagina_inteira is None:
        print(f"ERROR: Falha ao acessar a página: {current_page_url}. Parando scraping.")
        break

    lista_noticias = pagina_inteira.find("div", attrs={"class": "part"})
    if lista_noticias: # Verificar se 'part' foi encontrado
        lista_noticias = lista_noticias.find_all("div", attrs={"class": "item"})
    else:
        print(f"WARNING: Não foi possível encontrar a lista de notícias na página: {current_page_url}. Pulando para a próxima página (se houver).")
        lista_noticias = [] # Garante que é iterável mesmo sem notícias

    for noticia in lista_noticias:
        # titulo
        try:
            titulo = noticia.find("div", attrs={"class": "tit"}).text.strip()
            print(f"DEBUG - Título: {titulo}")
        except:
            titulo = ""
            print(f"WARNING: Título não encontrado para uma notícia na página: {current_page_url}")

        #link
        link_noticia = ""
        relative_link = ""
        try:
            link_tag = noticia.find("a")
            if link_tag and "href" in link_tag.attrs:
                relative_link = link_tag["href"]
                # Usar urljoin para resolver links relativos corretamente em relação à base do site
                link_noticia = urllib.parse.urljoin(base_site_url, relative_link)
                print(f"DEBUG - Relative Link: {relative_link}")
                print(f"DEBUG - Absolute Link: {link_noticia}")
            else:
                print(f"WARNING: Não foi encontrado link ('a' tag ou 'href') para a notícia: {titulo} na página: {current_page_url}")
        except Exception as e:
            print(f"ERROR: Falha ao extrair link para a notícia: {titulo} na página: {current_page_url}. Erro: {e}")
            link_noticia = ""

        # data e horário
        data = ""
        hora = ""
        data_hora_elements = noticia.find_all("span",attrs={"class": "time"})
        if data_hora_elements:
            data_hora_text = data_hora_elements[0].text.strip()
            partes_tempo = data_hora_text.split(" ")
            data = partes_tempo[0] if len(partes_tempo) > 0 else ""
            hora = partes_tempo[1] if len(partes_tempo) > 1 else ""
        print(f"DEBUG - Data: {data}, Hora: {hora}")

        if link_noticia: # Só tenta acessar o conteúdo se tiver um link válido
            conteudo = acessa_pagina (link_noticia)
            if conteudo is None:
                print(f"WARNING: Conteúdo não obtido para a notícia: {titulo} ({link_noticia})")
                continue # Pular para a próxima notícia se houver erro

            paragrafos_div = conteudo.find("div", attrs={"id" : "detailContent"})
            lista_paragrafos = []
            if paragrafos_div:
                paragrafos = paragrafos_div.find_all("p")
                for paragrafo in paragrafos:
                    lista_paragrafos.append(paragrafo.text.strip())
            else:
                print(f"WARNING: Não foi possível encontrar o conteúdo do parágrafo para: {link_noticia}")

            print(f"DEBUG - Parágrafos coletados: {len(lista_paragrafos)}")
            # função para inserir dados coletados no banco
            dados = {
                "titulo": titulo,
                "link": link_noticia,
                "data": data,
                "hora": hora,
                "paragrafo": lista_paragrafos
            }
            inserir_no_banco(dados,link_noticia)
            print("###")
        else:
            print(f"WARNING: Pulando notícia devido a link vazio para: {titulo}")

    # Lógica para encontrar o link da próxima página dinamicamente
    next_page_link_href = None

    # --- Attempt 1: Search for 'Next' or '>>' text or rel='next' ---
    # Prioritizes links within common pagination areas (div, ul, nav)
    # Added 'list-pages' to the regex for class names, a common pagination class
    pagination_areas = pagina_inteira.find_all(['div', 'ul', 'nav'], class_=re.compile(r'(page|pagi|nav|list-pages)', re.IGNORECASE))

    for area in pagination_areas:
        next_link_candidate = area.find('a', text=re.compile(r'Next|>>', re.IGNORECASE))
        if next_link_candidate and 'href' in next_link_candidate.attrs:
            next_page_link_href = next_link_candidate['href']
            print(f"DEBUG: Attempt 1 - Found next page link by text/rel: {next_page_link_href}")
            break # Found, can exit

    # If not found by text, try to find by rel='next'
    if not next_page_link_href:
        rel_next_link = pagina_inteira.find('a', rel='next')
        if rel_next_link and 'href' in rel_next_link.attrs:
            next_page_link_href = rel_next_link['href']
            print(f"DEBUG: Attempt 1 - Found next page link by rel='next': {next_page_link_href}")

    # --- Attempt 2: Fallback to numerical pattern if Attempt 1 fails ---
    if not next_page_link_href:
        # Extract base part of the URL (e.g., 'https://english.news.cn/list/china-science')
        # This regex handles both 'china-science.htm' and 'china-science_N.htm'
        base_url_match = re.match(r'^(https?://.+/list/.+?)(?:_\d+)?\.htm$', current_page_url)
        if base_url_match:
            base_url_prefix = base_url_match.group(1) # e.g., 'https://english.news.cn/list/china-science'

            # Extract current page number
            current_page_num_match = re.search(r'_(\d+)\.htm$', current_page_url)
            current_page_num = int(current_page_num_match.group(1)) if current_page_num_match else 1

            # Construct expected next page URL segment (e.g., '_2.htm' if current is '.htm', or '_3.htm' if current is '_2.htm')
            expected_next_page_segment = f"_{current_page_num + 1}.htm"

            # Search for any link whose href matches this expected segment
            all_links = pagina_inteira.find_all('a', href=True)
            for link in all_links:
                href = link['href']
                # Check if href contains the numerical pattern for the next page
                if expected_next_page_segment in href:
                    # Further check if the resolved absolute URL matches the expected next page pattern
                    potential_next_abs_url = urllib.parse.urljoin(current_page_url, href)
                    if potential_next_abs_url == f"{base_url_prefix}{expected_next_page_segment}":
                        next_page_link_href = href
                        print(f"DEBUG: Attempt 2 (Fallback) - Found numerical next page link: {next_page_link_href}")
                        break
        # Special case for the first page if it doesn't have an explicit '_1.htm' but is just '.htm'
        elif current_page_url.endswith('/china-science.htm'):
             expected_next_page_segment = '_2.htm'
             all_links = pagina_inteira.find_all('a', href=True)
             for link in all_links:
                 href = link['href']
                 potential_next_abs_url = urllib.parse.urljoin(current_page_url, href)
                 # Check if the resolved URL ends with the expected _2.htm
                 if potential_next_abs_url.endswith(expected_next_page_segment):
                     # Also ensure the beginning of the URL matches the base
                     if potential_next_abs_url.startswith(current_page_url.replace('.htm', '')):
                        next_page_link_href = href
                        print(f"DEBUG: Attempt 2 (Fallback) - Found first numerical next page link: {next_page_link_href}")
                        break

    if next_page_link_href:
        # Resolve the relative link of the next page URL
        current_page_url = urllib.parse.urljoin(current_page_url, next_page_link_href)
        print(f"DEBUG: Próxima página encontrada: {current_page_url}")
    else:
        print(f"INFO: Nenhuma próxima página encontrada na página {current_page_url}. Encerrando paginação.")
        current_page_url = None # Interrupt the loop if no more pages are found

    time.sleep(1) # Pausa de 1 segundo entre as requisições de página para ser educado com o servidor

Processando página: https://english.news.cn/list/china-science.htm (Página 1 de 5)
Estamos na pagina: https://english.news.cn/list/china-science.htm
DEBUG - Título: Across China: Scientists observe plants' reproductive adaptations amid droughts on Qinghai-Tibet Plateau2026-06-02 19:04:15
DEBUG - Relative Link: ../20260602/9eecdb51ce304f47b24622aac9d3e06e/c.html
DEBUG - Absolute Link: https://english.news.cn/20260602/9eecdb51ce304f47b24622aac9d3e06e/c.html
DEBUG - Data: 2026-06-02, Hora: 19:04:15
Estamos na pagina: https://english.news.cn/20260602/9eecdb51ce304f47b24622aac9d3e06e/c.html
DEBUG - Parágrafos coletados: 11
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: China's Long March-12B rocket completes successful maiden flight2026-06-01 20:51:15
DEBUG - Relative Link: ../20260601/07a188c35411425da7236cdaaecee71b/c.html
DEBUG - Absolute Link: https://english.news.cn/20260601/07a188c35411425da7236cdaaecee71b/c.html
DEBUG - Data: 2026-06-01, Hora: 20:51:15
Estamos na pagina: https://english.news.cn/20260601/07a188c35411425da7236cdaaecee71b/c.html
DEBUG - Parágrafos coletados: 17
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: China's Long March-12B rocket completes successful maiden flight2026-06-01 18:01:00
DEBUG - Relative Link: ../20260601/4cb3baccabf846608eb6de777590c211/c.html
DEBUG - Absolute Link: https://english.news.cn/20260601/4cb3baccabf846608eb6de777590c211/c.html
DEBUG - Data: 2026-06-01, Hora: 18:01:00
Estamos na pagina: https://english.news.cn/20260601/4cb3baccabf846608eb6de777590c211/c.html
DEBUG - Parágrafos coletados: 13
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: China launches new test satellite for internet technology2026-05-31 09:01:00
DEBUG - Relative Link: ../20260531/a3c492c28afa43868ed5a3fca4e643b3/c.html
DEBUG - Absolute Link: https://english.news.cn/20260531/a3c492c28afa43868ed5a3fca4e643b3/c.html
DEBUG - Data: 2026-05-31, Hora: 09:01:00
Estamos na pagina: https://english.news.cn/20260531/a3c492c28afa43868ed5a3fca4e643b3/c.html
DEBUG - Parágrafos coletados: 4
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: China Focus: China's space station lands new batch of samples for experiments2026-05-30 16:20:15
DEBUG - Relative Link: ../20260530/85a2047d3289430fb87b719719d48026/c.html
DEBUG - Absolute Link: https://english.news.cn/20260530/85a2047d3289430fb87b719719d48026/c.html
DEBUG - Data: 2026-05-30, Hora: 16:20:15
Estamos na pagina: https://english.news.cn/20260530/85a2047d3289430fb87b719719d48026/c.html
DEBUG - Parágrafos coletados: 9
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: Shenzhou-21 astronauts arrive in Beijing2026-05-30 09:51:00
DEBUG - Relative Link: ../20260530/d62a9ffe5e31434f8756ea3a98497f74/c.html
DEBUG - Absolute Link: https://english.news.cn/20260530/d62a9ffe5e31434f8756ea3a98497f74/c.html
DEBUG - Data: 2026-05-30, Hora: 09:51:00
Estamos na pagina: https://english.news.cn/20260530/d62a9ffe5e31434f8756ea3a98497f74/c.html
DEBUG - Parágrafos coletados: 4
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: China Focus: Shenzhou-21 astronauts return to Earth after record 210-day mission2026-05-30 00:47:45
DEBUG - Relative Link: ../20260530/a89b90d44f9047e99d9f46037b1080c2/c.html
DEBUG - Absolute Link: https://english.news.cn/20260530/a89b90d44f9047e99d9f46037b1080c2/c.html
DEBUG - Data: 2026-05-30, Hora: 00:47:45
Estamos na pagina: https://english.news.cn/20260530/a89b90d44f9047e99d9f46037b1080c2/c.html
DEBUG - Parágrafos coletados: 83
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: All Shenzhou-21 astronauts out of return capsule in good health2026-05-29 21:32:00
DEBUG - Relative Link: ../20260529/71a7238829f64e6fb67b09fe7c5a9c16/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/71a7238829f64e6fb67b09fe7c5a9c16/c.html
DEBUG - Data: 2026-05-29, Hora: 21:32:00
Estamos na pagina: https://english.news.cn/20260529/71a7238829f64e6fb67b09fe7c5a9c16/c.html
DEBUG - Parágrafos coletados: 2
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: China Focus: Digital technologies proving smart choice for Chinese education2026-05-29 21:08:15
DEBUG - Relative Link: ../20260529/1374339acdd747008f15694c3755be21/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/1374339acdd747008f15694c3755be21/c.html
DEBUG - Data: 2026-05-29, Hora: 21:08:15
Estamos na pagina: https://english.news.cn/20260529/1374339acdd747008f15694c3755be21/c.html
DEBUG - Parágrafos coletados: 26
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: Shenzhou-22 return capsule touches down, astronauts all sound2026-05-29 20:53:00
DEBUG - Relative Link: ../20260529/3d295320f5c94b898e7e32fb9f356381/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/3d295320f5c94b898e7e32fb9f356381/c.html
DEBUG - Data: 2026-05-29, Hora: 20:53:00
Estamos na pagina: https://english.news.cn/20260529/3d295320f5c94b898e7e32fb9f356381/c.html
DEBUG - Parágrafos coletados: 55
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: First Shenzhou-21 astronaut out of return capsule2026-05-29 20:47:30
DEBUG - Relative Link: ../20260529/ac12ff7968e34b58a5d1835495860578/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/ac12ff7968e34b58a5d1835495860578/c.html
DEBUG - Data: 2026-05-29, Hora: 20:47:30
Estamos na pagina: https://english.news.cn/20260529/ac12ff7968e34b58a5d1835495860578/c.html
DEBUG - Parágrafos coletados: 1
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: Shenzhou-22 return capsule touches down on Earth2026-05-29 20:12:15
DEBUG - Relative Link: ../20260529/693e955926894f4583d40307601416a0/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/693e955926894f4583d40307601416a0/c.html
DEBUG - Data: 2026-05-29, Hora: 20:12:15
Estamos na pagina: https://english.news.cn/20260529/693e955926894f4583d40307601416a0/c.html
DEBUG - Parágrafos coletados: 1
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: Main parachute of Shenzhou-22 return capsule deployed 2026-05-29 19:57:45
DEBUG - Relative Link: ../20260529/f56de4e1607444d7a221dafc4617467c/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/f56de4e1607444d7a221dafc4617467c/c.html
DEBUG - Data: 2026-05-29, Hora: 19:57:45
Estamos na pagina: https://english.news.cn/20260529/f56de4e1607444d7a221dafc4617467c/c.html
DEBUG - Parágrafos coletados: 9
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: Shenzhou-22 propulsion capsule separates from return capsule2026-05-29 19:48:30
DEBUG - Relative Link: ../20260529/dcfa402b6e414a018d62a1ea2bfcef3a/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/dcfa402b6e414a018d62a1ea2bfcef3a/c.html
DEBUG - Data: 2026-05-29, Hora: 19:48:30
Estamos na pagina: https://english.news.cn/20260529/dcfa402b6e414a018d62a1ea2bfcef3a/c.html
DEBUG - Parágrafos coletados: 1
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: Shenzhou-22 orbital capsule separates from return capsule2026-05-29 19:21:30
DEBUG - Relative Link: ../20260529/4d36e22268f24dbba2d41c0fa08cb9f9/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/4d36e22268f24dbba2d41c0fa08cb9f9/c.html
DEBUG - Data: 2026-05-29, Hora: 19:21:30
Estamos na pagina: https://english.news.cn/20260529/4d36e22268f24dbba2d41c0fa08cb9f9/c.html
DEBUG - Parágrafos coletados: 1
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: China releases role model stories to honor science and technology workers2026-05-29 18:06:30
DEBUG - Relative Link: ../20260529/b8db1e68be4b45439179b6f709094ba9/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/b8db1e68be4b45439179b6f709094ba9/c.html
DEBUG - Data: 2026-05-29, Hora: 18:06:30
Estamos na pagina: https://english.news.cn/20260529/b8db1e68be4b45439179b6f709094ba9/c.html
DEBUG - Parágrafos coletados: 6
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: Mathematics research adds up for smarter satellite calibration2026-05-29 16:19:15
DEBUG - Relative Link: ../20260529/4d9f7b315b93470c8c717af4b83bac38/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/4d9f7b315b93470c8c717af4b83bac38/c.html
DEBUG - Data: 2026-05-29, Hora: 16:19:15
Estamos na pagina: https://english.news.cn/20260529/4d9f7b315b93470c8c717af4b83bac38/c.html
DEBUG - Parágrafos coletados: 9
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: China's Shenzhou-22 spaceship undocks from space station combination2026-05-29 16:03:15
DEBUG - Relative Link: ../20260529/8626ff28228049fca5584bb62f5bfc54/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/8626ff28228049fca5584bb62f5bfc54/c.html
DEBUG - Data: 2026-05-29, Hora: 16:03:15
Estamos na pagina: https://english.news.cn/20260529/8626ff28228049fca5584bb62f5bfc54/c.html
DEBUG - Parágrafos coletados: 5
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: Novel robots help children with SMA defy motor loss: study2026-05-29 15:06:45
DEBUG - Relative Link: ../20260529/8e8b18314ce248cab01b556eeb2bc970/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/8e8b18314ce248cab01b556eeb2bc970/c.html
DEBUG - Data: 2026-05-29, Hora: 15:06:45
Estamos na pagina: https://english.news.cn/20260529/8e8b18314ce248cab01b556eeb2bc970/c.html
DEBUG - Parágrafos coletados: 11
Link já existe no banco. Esta informação não será inserida novamente
###
DEBUG - Título: China's Shenzhou-22 spaceship undocks from space station combination2026-05-29 15:06:30
DEBUG - Relative Link: ../20260529/b1d09e2995a24c40aabe70bc3e20b699/c.html
DEBUG - Absolute Link: https://english.news.cn/20260529/b1d09e2995a24c40aabe70bc3e20b699/c.html
DEBUG - Data: 2026-05-29, Hora: 15:06:30
Estamos na pagina: https://english.news.cn/20260529/b1d09e2995a24c40aabe70bc3e20b699/c.html
DEBUG - Parágrafos coletados: 1
Link já existe no banco. Esta informação não será inserida novamente
###
INFO: Nenhuma próxima página encontrada na página https://english.news.cn/list/china-science.htm. Encerrando paginação.

In [10]:
import pandas as pd
import json

## Abrindo o rquivo json
with open("nota_china.json") as f:
  raw = json.load(f)

df = pd.DataFrame.from_dict(raw["_default"], orient="index")

df

,titulo,link,data,hora,paragrafo
1,Across China: Scientists observe plants' repro...,https://english.news.cn/20260602/9eecdb51ce304...,2026-06-02,19:04:15,"[XINING, June 2 (Xinhua) -- A new study by Chi..."
2,China's Long March-12B rocket completes succes...,https://english.news.cn/20260601/07a188c354114...,2026-06-01,20:51:15,"[, A Long March-12B Y1 carrier rocket blasts o..."
3,China's Long March-12B rocket completes succes...,https://english.news.cn/20260601/4cb3baccabf84...,2026-06-01,18:01:00,"[, A Long March-12B Y1 carrier rocket blasts o..."
4,China launches new test satellite for internet...,https://english.news.cn/20260531/a3c492c28afa4...,2026-05-31,09:01:00,"[XICHANG, May 31 (Xinhua) -- China successfull..."
5,China Focus: China's space station lands new b...,https://english.news.cn/20260530/85a2047d32894...,2026-05-30,16:20:15,"[BEIJING, May 30 (Xinhua) -- A total of approx..."
6,Shenzhou-21 astronauts arrive in Beijing2026-0...,https://english.news.cn/20260530/d62a9ffe5e314...,2026-05-30,09:51:00,"[BEIJING, May 30 (Xinhua) -- The Shenzhou-21 c..."
7,China Focus: Shenzhou-21 astronauts return to ...,https://english.news.cn/20260530/a89b90d44f904...,2026-05-30,00:47:45,"[, The return capsule of the Shenzhou-22 space..."
8,All Shenzhou-21 astronauts out of return capsu...,https://english.news.cn/20260529/71a7238829f64...,2026-05-29,21:32:00,"[JIUQUAN, May 29 (Xinhua) -- The three astrona..."
9,China Focus: Digital technologies proving smar...,https://english.news.cn/20260529/1374339acdd74...,2026-05-29,21:08:15,"[HANGZHOU, May 29 (Xinhua) -- Smart sports sys..."
10,"Shenzhou-22 return capsule touches down, astro...",https://english.news.cn/20260529/3d295320f5c94...,2026-05-29,20:53:00,"[, The return capsule of the Shenzhou-22 space..."
11,First Shenzhou-21 astronaut out of return caps...,https://english.news.cn/20260529/ac12ff7968e34...,2026-05-29,20:47:30,"[JIUQUAN, May 29 (Xinhua) -- Zhang Lu, command..."
12,Shenzhou-22 return capsule touches down on Ear...,https://english.news.cn/20260529/693e955926894...,2026-05-29,20:12:15,"[JIUQUAN, May 29 (Xinhua) -- The return capsul..."
13,Main parachute of Shenzhou-22 return capsule d...,https://english.news.cn/20260529/f56de4e160744...,2026-05-29,19:57:45,"[, The return capsule of the Shenzhou-22 space..."
14,Shenzhou-22 propulsion capsule separates from ...,https://english.news.cn/20260529/dcfa402b6e414...,2026-05-29,19:48:30,"[JIUQUAN, May 29 (Xinhua) -- The propulsion ca..."
15,Shenzhou-22 orbital capsule separates from ret...,https://english.news.cn/20260529/4d36e22268f24...,2026-05-29,19:21:30,"[JIUQUAN, May 29 (Xinhua) -- The orbital capsu..."
16,China releases role model stories to honor sci...,https://english.news.cn/20260529/b8db1e68be4b4...,2026-05-29,18:06:30,"[BEIJING, May 29 (Xinhua) -- The Publicity Dep..."
17,Mathematics research adds up for smarter satel...,https://english.news.cn/20260529/4d9f7b315b934...,2026-05-29,16:19:15,"[CHANGSHA, May 29 (Xinhua) -- Chinese research..."
18,China's Shenzhou-22 spaceship undocks from spa...,https://english.news.cn/20260529/8626ff2822804...,2026-05-29,16:03:15,"[JIUQUAN, May 29 (Xinhua) -- China's Shenzhou-..."
19,Novel robots help children with SMA defy motor...,https://english.news.cn/20260529/8e8b18314ce24...,2026-05-29,15:06:45,"[BEIJING, May 29 (Xinhua) -- In a clinical tri..."
20,China's Shenzhou-22 spaceship undocks from spa...,https://english.news.cn/20260529/b1d09e2995a24...,2026-05-29,15:06:30,"[JIUQUAN, May 29 (Xinhua) -- China's Shenzhou-..."

In [11]:
# saber quantidade de linhas e colunas do dataframe
df.shape

(20, 5)

In [12]:
# saber colunas disponiveis
df.columns

Index(['titulo', 'link', 'data', 'hora', 'paragrafo'], dtype='object')

In [13]:
# selecionar uma coluna em especifico
df["titulo"]

1     Across China: Scientists observe plants' repro...
2     China's Long March-12B rocket completes succes...
3     China's Long March-12B rocket completes succes...
4     China launches new test satellite for internet...
5     China Focus: China's space station lands new b...
6     Shenzhou-21 astronauts arrive in Beijing2026-0...
7     China Focus: Shenzhou-21 astronauts return to ...
8     All Shenzhou-21 astronauts out of return capsu...
9     China Focus: Digital technologies proving smar...
10    Shenzhou-22 return capsule touches down, astro...
11    First Shenzhou-21 astronaut out of return caps...
12    Shenzhou-22 return capsule touches down on Ear...
13    Main parachute of Shenzhou-22 return capsule d...
14    Shenzhou-22 propulsion capsule separates from ...
15    Shenzhou-22 orbital capsule separates from ret...
16    China releases role model stories to honor sci...
17    Mathematics research adds up for smarter satel...
18    China's Shenzhou-22 spaceship undocks from spa...
19    Novel robots help children with SMA defy motor...
20    China's Shenzhou-22 spaceship undocks from spa...
Name: titulo, dtype: object

In [14]:
# delimitar colunas do dataframe
df_delimitado = df[["titulo", "data"]]
df_delimitado

                                               titulo        data
1   Across China: Scientists observe plants' repro...  2026-06-02
2   China's Long March-12B rocket completes succes...  2026-06-01
3   China's Long March-12B rocket completes succes...  2026-06-01
4   China launches new test satellite for internet...  2026-05-31
5   China Focus: China's space station lands new b...  2026-05-30
6   Shenzhou-21 astronauts arrive in Beijing2026-0...  2026-05-30
7   China Focus: Shenzhou-21 astronauts return to ...  2026-05-30
8   All Shenzhou-21 astronauts out of return capsu...  2026-05-29
9   China Focus: Digital technologies proving smar...  2026-05-29
10  Shenzhou-22 return capsule touches down, astro...  2026-05-29
11  First Shenzhou-21 astronaut out of return caps...  2026-05-29
12  Shenzhou-22 return capsule touches down on Ear...  2026-05-29
13  Main parachute of Shenzhou-22 return capsule d...  2026-05-29
14  Shenzhou-22 propulsion capsule separates from ...  2026-05-29
15  Shenzhou-22 orbital capsule separates from ret...  2026-05-29
16  China releases role model stories to honor sci...  2026-05-29
17  Mathematics research adds up for smarter satel...  2026-05-29
18  China's Shenzhou-22 spaceship undocks from spa...  2026-05-29
19  Novel robots help children with SMA defy motor...  2026-05-29
20  China's Shenzhou-22 spaceship undocks from spa...  2026-05-29

In [15]:
# primeiras (head), ultimas (tail) e linhas aleatórias (sample)
df.head(10)

,titulo,link,data,hora,paragrafo
1,Across China: Scientists observe plants' repro...,https://english.news.cn/20260602/9eecdb51ce304...,2026-06-02,19:04:15,"[XINING, June 2 (Xinhua) -- A new study by Chi..."
2,China's Long March-12B rocket completes succes...,https://english.news.cn/20260601/07a188c354114...,2026-06-01,20:51:15,"[, A Long March-12B Y1 carrier rocket blasts o..."
3,China's Long March-12B rocket completes succes...,https://english.news.cn/20260601/4cb3baccabf84...,2026-06-01,18:01:00,"[, A Long March-12B Y1 carrier rocket blasts o..."
4,China launches new test satellite for internet...,https://english.news.cn/20260531/a3c492c28afa4...,2026-05-31,09:01:00,"[XICHANG, May 31 (Xinhua) -- China successfull..."
5,China Focus: China's space station lands new b...,https://english.news.cn/20260530/85a2047d32894...,2026-05-30,16:20:15,"[BEIJING, May 30 (Xinhua) -- A total of approx..."
6,Shenzhou-21 astronauts arrive in Beijing2026-0...,https://english.news.cn/20260530/d62a9ffe5e314...,2026-05-30,09:51:00,"[BEIJING, May 30 (Xinhua) -- The Shenzhou-21 c..."
7,China Focus: Shenzhou-21 astronauts return to ...,https://english.news.cn/20260530/a89b90d44f904...,2026-05-30,00:47:45,"[, The return capsule of the Shenzhou-22 space..."
8,All Shenzhou-21 astronauts out of return capsu...,https://english.news.cn/20260529/71a7238829f64...,2026-05-29,21:32:00,"[JIUQUAN, May 29 (Xinhua) -- The three astrona..."
9,China Focus: Digital technologies proving smar...,https://english.news.cn/20260529/1374339acdd74...,2026-05-29,21:08:15,"[HANGZHOU, May 29 (Xinhua) -- Smart sports sys..."
10,"Shenzhou-22 return capsule touches down, astro...",https://english.news.cn/20260529/3d295320f5c94...,2026-05-29,20:53:00,"[, The return capsule of the Shenzhou-22 space..."

In [16]:
df.describe(include="all")

,titulo,link,data,hora,paragrafo
count,20,20,20,20,20
unique,20,20,5,20,20
top,Across China: Scientists observe plants' repro...,https://english.news.cn/20260602/9eecdb51ce304...,2026-05-29,19:04:15,"[XINING, June 2 (Xinhua) -- A new study by Chi..."
freq,1,1,13,1,1

In [17]:
df.isnull().sum()

titulo       0
link         0
data         0
hora         0
paragrafo    0
dtype: int64

In [19]:
# 1. Converter a coluna de data para o formato datetime do Pandas
df['data_dt'] = pd.to_datetime(df['data'], format='%Y-%m-%d', errors='coerce')

# 2. Contar quantas notícias temos por dia
noticias_por_dia = df['data_dt'].value_counts().sort_index()

display(noticias_por_dia)

data_dt
2026-05-29    13
2026-05-30     3
2026-05-31     1
2026-06-01     2
2026-06-02     1
Name: count, dtype: int64

In [ ]:
import matplotlib.pyplot as plt

# Criando o gráfico
plt.figure(figsize=(15, 10))
noticias_por_dia.plot(kind='bar', color='red')

# Adicionando títulos e rótulos
plt.title('Quantidade de Notas à Imprensa por Data')
plt.xlabel('Data da Publicação')
plt.ylabel('Número de Notas')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.show()

In [ ]:
temas = ['AI', 'Big Tech', 'Brazil', 'United States', 'Europe']
frequencia = {}

for tema_singular in temas:
    # Conta em quantos títulos a palavra aparece
    frequencia[tema_singular] = df['titulo'].str.contains(tema_singular, case=False).sum()

# Converter para série para facilitar a plotagem
ser_freq = pd.Series(frequencia)

plt.figure(figsize=(8, 4))
ser_freq.sort_values(ascending=False).plot(kind='barh', color='lightgreen')
plt.title('Menções nos Títulos das Notas')
plt.xlabel('Número de Menções')
plt.show()

In [21]:
import pandas as pd
import matplotlib.pyplot as plt

# 1.1 — Converter data para datetime
df['data_dt'] = pd.to_datetime(df['data'], format='%Y-%m-%d', errors='coerce')

# 1.2 — Juntar os parágrafos (que são listas) em um único texto
df['texto'] = df['paragrafo'].apply(lambda lista: ' '.join(lista) if isinstance(lista, list) else str(lista))

# 1.3 — Coluna com tudo junto e em minúsculas (facilita buscas)
df['texto_completo'] = (df['titulo'].fillna('') + ' ' + df['texto']).str.lower()

# 1.4 — Extrair a hora como número inteiro (de "19h20" tira o 19)
df['hora_int'] = df['hora'].str.extract(r'(\d{1,2})').astype(float)

# 1.5 — Colunas auxiliares de tempo
df['ano_mes'] = df['data_dt'].dt.to_period('M')
df['dia_semana'] = df['data_dt'].dt.day_name()
df['tamanho_texto'] = df['texto'].str.len()
df['qtd_paragrafos'] = df['paragrafo'].apply(lambda x: len(x) if isinstance(x, list) else 0)

print(f"Total de notas: {len(df)}")
print(f"Período: de {df['data_dt'].min().date()} até {df['data_dt'].max().date()}")
df[['titulo', 'data_dt', 'hora_int', 'qtd_paragrafos', 'tamanho_texto']].head()

Total de notas: 20
Período: de 2026-05-29 até 2026-06-02

,titulo,data_dt,hora_int,qtd_paragrafos,tamanho_texto
1,Across China: Scientists observe plants' repro...,2026-06-02,19.0,11,3152
2,China's Long March-12B rocket completes succes...,2026-06-01,20.0,17,3091
3,China's Long March-12B rocket completes succes...,2026-06-01,18.0,13,2120
4,China launches new test satellite for internet...,2026-05-31,9.0,4,610
5,China Focus: China's space station lands new b...,2026-05-30,16.0,9,2129

In [ ]:
# Duplicatas por link (cada nota deveria ter um link único)
print("Duplicatas por link:", df.duplicated(subset=['link']).sum())

# Duplicatas por título
print("Duplicatas por título:", df.duplicated(subset=['titulo']).sum())

In [ ]:
def buscar_termo(termo, onde='completo', mostrar=5):
    """
    Busca um termo nas notas do MRE.

    Parâmetros:
        termo (str): palavra ou expressão a buscar (não diferencia maiúsc/minúsc)
        onde (str): 'titulo', 'texto' ou 'completo' (título + corpo)
        mostrar (int): quantos resultados imprimir

    Retorna:
        DataFrame com as notas que contêm o termo
    """
    coluna = {
        'titulo': 'titulo',
        'texto': 'texto',
        'completo': 'texto_completo',
    }[onde]

    # busca case-insensitive; na=False ignora valores faltantes
    mascara = df[coluna].str.contains(termo, case=False, na=False, regex=False)
    resultado = df[mascara].sort_values('data_dt', ascending=False)

    print(f"🔎 Termo: '{termo}'  |  Onde: {onde}")
    print(f"📌 Notas encontradas: {len(resultado)} de {len(df)} ({len(resultado)/len(df)*100:.1f}%)")
    print("-" * 60)

    for _, row in resultado.head(mostrar).iterrows():
        data_str = row['data_dt'].strftime('%d/%m/%Y') if pd.notna(row['data_dt']) else '?'
        print(f"  • [{data_str}] {row['titulo']}")

    if len(resultado) > mostrar:
        print(f"  ... e mais {len(resultado) - mostrar} nota(s)")

    return resultado


# Exemplos de uso:
res = buscar_termo('AI', onde='completo', mostrar=5)

In [ ]:
# Buscar só no título
buscar_termo('AI', onde='titulo', mostrar=5)

In [ ]:
# Buscar uma expressão composta
buscar_termo('Big Tech', onde='completo', mostrar=5)

In [ ]:
def frequencia_termos(lista_termos, onde='completo'):
    """Conta em quantas notas cada termo da lista aparece."""
    coluna = {'titulo': 'titulo', 'texto': 'texto', 'completo': 'texto_completo'}[onde]
    freq = {}
    for termo in lista_termos:
        freq[termo] = df[coluna].str.contains(termo, case=False, na=False, regex=False).sum()
    return pd.Series(freq).sort_values(ascending=True)


# Lista mais ampla de países e temas
termos_interesse = [
    'United States', 'Brazil', 'Europe', 'America'
]

freq = frequencia_termos(termos_interesse, onde='completo')

# Gráfico
fig, ax = plt.subplots(figsize=(10, 6))
freq.plot(kind='barh', ax=ax, color='steelblue')
ax.set_title('Menções por país/região no texto completo das notas', fontsize=13)
ax.set_xlabel('Número de notas')
ax.grid(axis='x', linestyle='--', alpha=0.5)

# Anotar valores nas barras
for i, valor in enumerate(freq.values):
    ax.text(valor + 0.1, i, str(valor), va='center')

plt.tight_layout()
plt.show()

In [ ]:
# Notas por mês
notas_por_mes = df.groupby('ano_mes').size()

fig, ax = plt.subplots(figsize=(11, 4))
notas_por_mes.plot(kind='bar', ax=ax, color='teal')
ax.set_title('Volume de notas por mês', fontsize=13)
ax.set_xlabel('Ano-Mês')
ax.set_ylabel('Número de notas')
ax.grid(axis='y', linestyle='--', alpha=0.5)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

In [ ]:
import re
from collections import Counter

# Stopwords em português (lista pequena, suficiente para começar)
STOPWORDS_PT = {
    'a', 'of', 'on', 'the', 'in', 'at', 'this', 'that',
    'these',  # específicas do contexto
}


def palavras_mais_frequentes(serie_texto, top_n=20, min_tamanho=4):
    """Conta as palavras mais frequentes em uma coluna de texto."""
    todas_palavras = []
    for texto in serie_texto.dropna():
        # \w+ pega sequências de letras/números; flags re.UNICODE pra acentos
        palavras = re.findall(r'\b[a-záàâãéêíóôõúüç]+\b', texto.lower(), flags=re.UNICODE)
        palavras = [p for p in palavras if p not in STOPWORDS_PT and len(p) >= min_tamanho]
        todas_palavras.extend(palavras)
    return Counter(todas_palavras).most_common(top_n)


top_palavras = palavras_mais_frequentes(df['titulo'], top_n=20)
print("Top 20 palavras nos TÍTULOS:")
for palavra, contagem in top_palavras:
    print(f"  {palavra:25s} {contagem}")

# Gráfico
serie = pd.Series(dict(top_palavras)).sort_values(ascending=True)
fig, ax = plt.subplots(figsize=(10, 7))
serie.plot(kind='barh', ax=ax, color='coral')
ax.set_title('Top 20 palavras mais frequentes nos títulos das notas', fontsize=13)
ax.set_xlabel('Frequência')
ax.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

In [ ]:
def evolucao_termo(termo, onde='completo'):
    """Mostra quantas notas mencionam o termo por mês."""
    coluna = {'titulo': 'titulo', 'texto': 'texto', 'completo': 'texto_completo'}[onde]
    mascara = df[coluna].str.contains(termo, case=False, na=False, regex=False)
    return df[mascara].groupby('ano_mes').size()


# Comparar evolução de vários termos no tempo
termos_comparar = ['Brazil', 'USA', 'United States', 'Europe']

fig, ax = plt.subplots(figsize=(11, 5))
for termo in termos_comparar:
    serie = evolucao_termo(termo)
    if len(serie) > 0:
        serie.plot(ax=ax, marker='o', label=termo)

ax.set_title('Menções por mês (no texto completo das notas)', fontsize=13)
ax.set_xlabel('Ano-Mês')
ax.set_ylabel('Número de notas que mencionam o termo')
ax.legend()
ax.grid(linestyle='--', alpha=0.5)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

In [ ]:
import numpy as np

paises_analise = ['Brazil', 'United States', 'Israel', 'Argentina', 'China',
                  'Japan', 'German', 'Europe', 'Latin America']

# Para cada nota, marca quais países são mencionados
matriz_presenca = pd.DataFrame({
    pais: df['texto_completo'].str.contains(pais, case=False, na=False, regex=False).astype(int)
    for pais in paises_analise
})

# Matriz de co-ocorrência (multiplicação matricial: notas onde A E B aparecem)
coocorrencia = matriz_presenca.T.dot(matriz_presenca)

# Zerar a diagonal (não interessa um país com ele mesmo)
np.fill_diagonal(coocorrencia.values, 0)

# Heatmap simples com matplotlib
fig, ax = plt.subplots(figsize=(9, 7))
im = ax.imshow(coocorrencia, cmap='YlOrRd', aspect='auto')

ax.set_xticks(range(len(paises_analise)))
ax.set_yticks(range(len(paises_analise)))
ax.set_xticklabels(paises_analise, rotation=45, ha='right')
ax.set_yticklabels(paises_analise)
ax.set_title('Co-ocorrência: quantas notas mencionam dois países juntos', fontsize=13)

# Anotar os valores nas células
for i in range(len(paises_analise)):
    for j in range(len(paises_analise)):
        valor = coocorrencia.iloc[i, j]
        if valor > 0:
            ax.text(j, i, int(valor), ha='center', va='center',
                    color='black' if valor < coocorrencia.values.max()/2 else 'white',
                    fontsize=9)

plt.colorbar(im, ax=ax, label='Nº de notas em comum')
plt.tight_layout()
plt.show()